name = "multiplayer-js"
main = "src/index.js"
compatibility_date = "2024-05-12"

tail_consumers = [
    { service = "missing-consumer-xyz" }
]

[[durable_objects.bindings]]
name = "MULTIPLAYER_OBJECT"
class_name = "multiplayerObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["multiplayerObject"]
